"""Next Migration

Revision ID: 8d7898e27669
Revises: f8294cb448bf
Create Date: 2025-03-14 02:38:23.958591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7898e27669'
down_revision = 'f8294cb448bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('court_booking_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('court_booking_instructions')
        batch_op.drop_column('payment_info')

    # ### end Alembic commands ###
